#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses on the machine using hostname and awk.

# Use the hostname command to list all IPv4 addresses
hostname -I | awk '{for (i=1; i<=NF; i++) print $i}'
